#Cambia los nombres del contexto del evento
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Â¿QueÌ aporta la neuroeducacioÌn al educador?"] <- "Archivo1"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Clase (Particularidades de los seres humanos)"] <- "Archivo2"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Clase Presencial (Fuego y Cerebro)"] <- "Archivo3"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Documento de lectura"] <- "Archivo4"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: EvoluciÃ³n y CogniciÃ³n"] <- "Archivo5"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Memoria y Aprendizaje: Una revisiÃ³n de los aportes cognitivos"] <- "Archivo6" 
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Neuromitos"] <- "Archivo7"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Pauta evaluaciÃ³n disertaciÃ³n"] <- "Archivo8"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Ultima clase"] <- "Archivo9"
log$Contexto.del.evento[log$Contexto.del.evento == "Carpeta: Paper (documentos) para disertaciÃ³n"] <- "Carpeta"
log$Contexto.del.evento[log$Contexto.del.evento == "Chat: RevisiÃ³n de Foros"] <- "Chat"
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: El avance tecnolÃ³gico y los neuromitos"] <- "H5P1"
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: Herramienta de escritura Neuromitos"] <- "H5P2"
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: La memoria"] <- "H5P3" 
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: Memoria y aprendizaje"] <- "H5P4"
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: Neurociencias y educaciÃ³n"] <- "H5P5"
log$Contexto.del.evento[log$Contexto.del.evento == "Cuestionario: Â¿QuÃ© tiene de especial el cerebro Humano?"] <- "Cuestionario"
log$Contexto.del.evento[log$Contexto.del.evento == "Curso: BASES NEUROBIOLOGICAS DEL DESARROLLO I (PEDAGOGIA EN EDUCACION DIFERENCIAL)"] <- "CURSO"
log$Contexto.del.evento[log$Contexto.del.evento == "Encuestas predefinidas: bubuyhuyhb"] <- "Encuesta"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta:"] <- "Etiqueta1"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta: Etiqueta"] <- "Etiqueta3"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta: La invenciÃ³n del internet"] <- "Etiqueta4"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta: NeuroeducaciÃ³n"] <- "Etiqueta5"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta: Neuromitos versiÃ³n 2"] <- "Etiqueta6"
log$Contexto.del.evento[log$Contexto.del.evento == "Foro: Avisos"] <- "Foro1"
log$Contexto.del.evento[log$Contexto.del.evento == "Foro: Neuromitos que circulan en internet"] <- "Foro2"
log$Contexto.del.evento[log$Contexto.del.evento == "Foro: Prometeo"] <- "Foro3"
log$Contexto.del.evento[log$Contexto.del.evento == "Foro: Temas de disertaciÃ³n"] <- "Foro4"
log$Contexto.del.evento[log$Contexto.del.evento == "Tarea: InfografÃa"] <- "Tarea Inf."
log$Contexto.del.evento[log$Contexto.del.evento == "Tarea: Neuromitos versiÃ³n 2"] <- "Tarea Neu2"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: Acceso al drive de la asignatura"] <- "URL Drive"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: Video: Fuentes de informaciÃ³n"] <- "URLvideo"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: VIdeo: Fuentes de informaciÃ³n 2"] <- "URLvideo2"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: VIdeo: Herramienta de escritura-Neuromitos"] <- "URLvideo3"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: Video: Symbaloo"] <- "URLvideo4"

#Cambia nombre de profesor, investigador y admin
log$Nombre.completo.del.usuario[log$Nombre.completo.del.usuario == "Sergio GonzÃ¡lez"] <- "Investigador"
log$Nombre.completo.del.usuario[log$Nombre.completo.del.usuario == "Alan Maldonado M."] <- "Profesor"
log$Nombre.completo.del.usuario[log$Nombre.completo.del.usuario == "Administrador pregrado virtual"] <- "Profesor"

#Cambia nombre de eventos
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "AlgÃºn contenido ha sido publicado."] <- "Contenido publicado"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "CalificaciÃ³n XML exportada"] <- "Calificación XML exportada"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "FinalizaciÃ³n de actividad de curso actualizada"] <- "Finalización de actividad de curso actualizada"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "Informe de participaciÃ³n visto"] <- "Informe de participación visto"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "Instancia de inscripciÃ³n creada"] <- "Instancia de inscripción creada"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "Instancia del mÃ³dulo del curso visualizada"] <- "Instancia del módulo del curso visualizada"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "MÃ³dulo de curso actualizado?"] <- "Módulo del curso actualizado"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "MÃ³dulo de curso creado"] <- "Módulo del curso creado"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "MÃ³dulo de curso visto"] <- "Módulo del curso visto"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "PÃ¡gina de ediciÃ³n del cuestionario visitada"] <- "Página de edición del cuestionario visitado"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "Se ha borrado la suscripciÃ³n de esta discusiÃ³n"] <- "Se ha borrado la suscripción a discusión"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "SecciÃ³n de curso actualizado"] <- "Sección de curso actualizado"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "SecciÃ³n del curso creada"] <- "Sección del curso creada"
dscompleto$Nombre.evento[dscompleto$Nombre.evento == "VisualizaciÃ³n de las Calificaciones"] <- "Visualización de calificaciones"


