#Cambia los nombres del contexto del evento
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: ¿Qué aporta la neuroeducación al educador?04"] <- "Archivo1"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: ¿Qué aporta la neuroeducación al educador?20"] <- "Archivo1"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: ¿Qué aporta la neuroeducación al educador?it"] <- "Archivo1"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: ¿Qué aporta la neuroeducación al educador?ty"] <- "Archivo1"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Clase (Particularidades de los seres humanos)"] <- "Archivo2"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Clase Presencial (Fuego y Cerebro)"] <- "Archivo3"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Documento de lectura"] <- "Archivo4"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Evolución y Cognición"] <- "Archivo5"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Memoria y Aprendizaje: Una revisión de los aportes cognitivos"] <- "Archivo6" 
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Neuromitos"] <- "Archivo7"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Pauta evaluación disertación"] <- "Archivo8"
log$Contexto.del.evento[log$Contexto.del.evento == "Archivo: Ultima clase"] <- "Archivo9"
log$Contexto.del.evento[log$Contexto.del.evento == "Carpeta: Paper (documentos) para disertación"] <- "Carpeta"
log$Contexto.del.evento[log$Contexto.del.evento == "Chat: Revisión de Foros"] <- "Chat"
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: El avance tecnológico y los neuromitos"] <- "H5P1"
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: Herramienta de escritura Neuromitos"] <- "H5P2"
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: La memoria"] <- "H5P3" 
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: Memoria y aprendizaje"] <- "H5P4"
log$Contexto.del.evento[log$Contexto.del.evento == "Contenido Interactivo: Neurociencias y educación"] <- "H5P5"
log$Contexto.del.evento[log$Contexto.del.evento == "Cuestionario: ¿Qué tiene de especial el cerebro Humano?"] <- "Cuestionario"
log$Contexto.del.evento[log$Contexto.del.evento == "Curso: BASES NEUROBIOLOGICAS DEL DESARROLLO I (PEDAGOGIA EN EDUCACION DIFERENCIAL)"] <- "CURSO"
log$Contexto.del.evento[log$Contexto.del.evento == "Encuestas predefinidas: bubuyhuyhb"] <- "Encuesta"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta:"] <- "Etiqueta1"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta: Etiqueta"] <- "Etiqueta3"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta: La invención del internet"] <- "Etiqueta4"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta: Neuroeducación"] <- "Etiqueta5"
log$Contexto.del.evento[log$Contexto.del.evento == "Etiqueta: Neuromitos versión 2"] <- "Etiqueta6"
log$Contexto.del.evento[log$Contexto.del.evento == "Foro: Avisos"] <- "Foro1"
log$Contexto.del.evento[log$Contexto.del.evento == "Foro: Neuromitos que circulan en internet"] <- "Foro2"
log$Contexto.del.evento[log$Contexto.del.evento == "Foro: Prometeo"] <- "Foro3"
log$Contexto.del.evento[log$Contexto.del.evento == "Foro: Temas de disertación"] <- "Foro4"
log$Contexto.del.evento[log$Contexto.del.evento == "Tarea: Infografía"] <- "Tarea Inf."
log$Contexto.del.evento[log$Contexto.del.evento == "Tarea: Neuromitos versión 2"] <- "Tarea Neu2"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: Acceso al drive de la asignatura"] <- "URL Drive"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: Video: Fuentes de información"] <- "URLvideo"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: VIdeo: Fuentes de información 2"] <- "URLvideo2"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: VIdeo: Herramienta de escritura-Neuromitos"] <- "URLvideo3"
log$Contexto.del.evento[log$Contexto.del.evento == "URL: Video: Symbaloo"] <- "URLvideo4"

log$Nombre.completo.del.usuario[log$Nombre.completo.del.usuario == "Sergio González"] <- "Investigador"
log$Nombre.completo.del.usuario[log$Nombre.completo.del.usuario == "Alan Maldonado M."] <- "Profesor"
log$Nombre.completo.del.usuario[log$Nombre.completo.del.usuario == "Administrador pregrado virtual"] <- "Profesor"
